# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test TP Link Archer C1200 API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_archer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Unit Testing + coverage
      run: |
        coverage run tests/test_archer1200.py -u -d
        coverage report
    - name: Test with pytest unittest
      run: |
        pytest -v tests/test_archer1200.py

  lint:
      runs-on: ubuntu-latest
      name: Lint with flake8
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
            python-version: 3.10.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
